---
- name: lab_release
  shell: echo $(lsb_release -cs)
  register: lab_release_out

- name: set_fact
  set_fact:
    lsb_release:    "{{ lab_release_out.stdout }}"
    service_name_1: "{{ service_name_1 }}"
    service_port_1: "{{ service_port_1 }}"
    target_name_1:  "{{ target_name_1 }}"
    service_name_2: "{{ service_name_2 }}"
    service_port_2: "{{ service_port_2 }}"
    target_name_2:  "{{ target_name_2 }}"

- debug:
    msg: "{{ lsb_release }}"

- name: Install apt packages
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: present

- name: Add key
  shell: curl -sL 'https://getenvoy.io/gpg' | sudo apt-key add -
  environment:
    HTTP_PROXY: 'http://proxy.internal:8080/'
    HTTPS_PROXY: 'http://proxy.internal:8080/'

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb {{ lsb_release }} stable"
    state: present

- name: Install envoy
  apt:
    pkg:
    - getenvoy-envoy
    state: present

- name: Create directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { path: '/etc/envoy',          mode: '0755' , state: 'directory' }
    - { path: '/run/envoy',          mode: '0755' , state: 'directory' }
    - { path: '/var/log/envoy.log',  mode: '0644' , state: 'touch'     }

- name: Create files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: 'envoy.service', mode: '0644', dest: '/lib/systemd/system/envoy.service'  }

- name: Create templates
  vars:
    service_name_1: "{{ service_name_1 }}"
    service_port_1: "{{ service_port_1 }}"
    target_name_1:  "{{ target_name_1 }}"
    service_name_2: "{{ service_name_2 }}"
    service_port_2: "{{ service_port_2 }}"
    target_name_2:  "{{ target_name_2 }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - { src: 'envoy.yaml.j2', mode: '0644', dest: '/etc/envoy/envoy.yaml' }


- name: restart service
  systemd:
    name: envoy
    state: restarted
    enabled: yes
    daemon_reload: yes